package selenide;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;
public class StudentTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void student() {
    driver.get("https://demoqa.com/automation-practice-form");
    driver.manage().window().setSize(new Dimension(1010, 714));
    driver.findElement(By.id("firstName")).click();
    driver.findElement(By.id("firstName")).sendKeys("Антон");
    driver.findElement(By.id("lastName")).click();
    driver.findElement(By.id("lastName")).sendKeys("Родин");
    driver.findElement(By.id("userEmail")).click();
    driver.findElement(By.id("userEmail")).sendKeys("asg@ya.ru");
    driver.findElement(By.cssSelector(".custom-radio:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".custom-radio:nth-child(1) > .custom-control-label")).click();
    driver.findElement(By.id("userNumber")).click();
    driver.findElement(By.id("userNumber")).sendKeys("9265879878");
    js.executeScript("window.scrollTo(0,200)");
    driver.findElement(By.id("dateOfBirthInput")).click();
    driver.findElement(By.cssSelector(".react-datepicker__month-select")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".react-datepicker__month-select"));
      dropdown.findElement(By.xpath("//option[. = 'June']")).click();
    }
    driver.findElement(By.cssSelector(".react-datepicker__month-select")).click();
    driver.findElement(By.cssSelector(".react-datepicker__year-select")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".react-datepicker__year-select"));
      dropdown.findElement(By.xpath("//option[. = '1980']")).click();
    }
    driver.findElement(By.cssSelector(".react-datepicker__year-select")).click();
    driver.findElement(By.cssSelector(".react-datepicker__day--010:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".subjects-auto-complete__value-container")).click();
    driver.findElement(By.id("react-select-2-option-0")).click();
    driver.findElement(By.cssSelector(".custom-checkbox:nth-child(1) > .custom-control-label")).click();
    driver.findElement(By.cssSelector(".custom-checkbox:nth-child(2) > .custom-control-label")).click();
    driver.findElement(By.cssSelector(".custom-checkbox:nth-child(3) > .custom-control-label")).click();
    driver.findElement(By.id("uploadPicture")).click();
    driver.findElement(By.id("uploadPicture")).sendKeys("C:\\fakepath\\error.log");
    driver.findElement(By.id("currentAddress")).click();
    driver.findElement(By.id("currentAddress")).sendKeys("Москва");
    driver.findElement(By.cssSelector(".css-1pahdxg-control .css-1wa3eu0-placeholder")).click();
    driver.findElement(By.id("react-select-3-option-1")).click();
    driver.findElement(By.cssSelector(".css-1wa3eu0-placeholder")).click();
    driver.findElement(By.id("react-select-4-option-0")).click();
    driver.findElement(By.id("submit")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(2)")).getText(), is("Антон Родин"));
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(7) > td:nth-child(2)")).getText(), is("Sports, Reading, Music"));
    driver.findElement(By.id("closeLargeModal")).click();
  }
}
