package selenide;// Generated by Selenium IDE
import com.codeborne.selenide.Configuration;
import com.codeborne.selenide.WebDriverRunner;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.Dimension;

import java.util.HashMap;
import java.util.Map;

import static com.codeborne.selenide.Condition.text;
import static com.codeborne.selenide.Selenide.*;
public class StudentTestSelenide {
  private Map<String, Object> vars;
  @BeforeEach
  public void setUp() {
    Configuration.browser = "chrome";
    vars = new HashMap<>();
  }
  @AfterEach
  public void tearDown() {
  }
  @Test
  public void student() {
    open("https://demoqa.com/automation-practice-form");
    WebDriverRunner.getWebDriver().manage().window().setSize(new Dimension(1010, 714));
    $("#firstName").click();
    $("#firstName").val("Антон");
    $("#lastName").click();
    $("#lastName").val("Родин");
    $("#userEmail").click();
    $("#userEmail").val("asg@ya.ru");
    $(".custom-radio:nth-child(1)").click();
    $(".custom-radio:nth-child(1) > .custom-control-label").click();
    $("#userNumber").click();
    $("#userNumber").val("9265879878");
    executeJavaScript("window.scrollTo(0,200)");
    $("#dateOfBirthInput").click();
    $(".react-datepicker__month-select").click();
    $(".react-datepicker__month-select").selectOption("June");
    $(".react-datepicker__month-select").click();
    $(".react-datepicker__year-select").click();
    $(".react-datepicker__year-select").selectOption("1980");
    $(".react-datepicker__year-select").click();
    $(".react-datepicker__day--010:nth-child(3)").click();
    $(".subjects-auto-complete__value-container").click();
    $("#react-select-2-option-0").click();
    $(".custom-checkbox:nth-child(1) > .custom-control-label").click();
    $(".custom-checkbox:nth-child(2) > .custom-control-label").click();
    $(".custom-checkbox:nth-child(3) > .custom-control-label").click();
    $("#uploadPicture").click();
    $("#uploadPicture").val("C:\\fakepath\\error.log");
    $("#currentAddress").click();
    $("#currentAddress").val("Москва");
    $(".css-1pahdxg-control .css-1wa3eu0-placeholder").click();
    $("#react-select-3-option-1").click();
    $(".css-1wa3eu0-placeholder").click();
    $("#react-select-4-option-0").click();
    $("#submit").click();
    $("tr:nth-child(1) > td:nth-child(2)").shouldHave(text("Антон Родин"));
    $("tr:nth-child(7) > td:nth-child(2)").shouldHave(text("Sports, Reading, Music"));
    $("#closeLargeModal").click();
  }
}
